---
- hosts: all
  vars:
    - spark_version: 1.3.1
    - postgresql_version: 9.4

  handlers:
    - name: delete miniconda installer
      command: rm miniconda.sh chdir={{ansible_env.HOME}}
    - name: delete spark installer
      command: rm spark-{{spark_version}}-bin-hadoop2.4.tgz

  tasks:
    - name: install packages
      sudo: yes
      apt: name={{item}} state=installed update_cache=yes
      with_items:
        - vim
        - emacs
        - zsh
        - tmux
        - git
        - python-setuptools
        - htop
        - postgresql-{{postgresql_version}}
        - postgresql-contrib-{{postgresql_version}}
        - libpq-dev
        - liblzma-dev
        - openjdk-7-jdk

    - name: stop postgres process
      command: sudo service postgresql stop

    - name: configure postgresql
      lineinfile: dest={{ansible_env.HOME}}/.bashrc regexp="^export.*postgresql" line="export PATH=/usr/lib/postgresql/9.4/bin:$PATH"

    - name: configure dotfiles
      git: repo=https://github.com/vitillo/dotfiles.git dest={{ansible_env.HOME}}/dotfiles

    - name: install dotfiles
      command: make chdir={{ansible_env.HOME}}/dotfiles creates={{ansible_env.HOME}}/.vimrc

    - name: install anaconda
      command: "{{item}} chdir={{ansible_env.HOME}} creates=miniconda"
      with_items:
        - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
        - chmod +x miniconda.sh
        - ./miniconda.sh -b -f 
      notify:
        - delete miniconda installer 

    - name: source anaconda
      lineinfile: dest={{ansible_env.HOME}}/.bashrc regexp="^export.*miniconda/bin" line="export PATH={{ansible_env.HOME}}/miniconda/bin:$PATH"

    - name: install common python packages
      command: "{{item}} chdir={{ansible_env.HOME}}"
      with_items:
        - miniconda/bin/conda update --yes conda
        - miniconda/bin/conda install --yes atlas numpy scipy matplotlib nose dateutil pandas flask

    - name: install spark
      command: "{{item}} chdir={{ansible_env.HOME}} creates=spark-{{spark_version}}-bin-hadoop2.4"
      with_items:
        - wget http://d3kbcqa49mib13.cloudfront.net/spark-{{spark_version}}-bin-hadoop2.4.tgz
        - tar -xzf spark-{{spark_version}}-bin-hadoop2.4.tgz
      notify:
        - delete spark installer

    - name: source spark
      lineinfile: dest={{ansible_env.HOME}}/.bashrc regexp="^export SPARK_HOME" line="export SPARK_HOME={{ansible_env.HOME}}/spark-{{spark_version}}-bin-hadoop2.4"

    - name: setup project dependencies
      command: "{{ansible_env.HOME}}/miniconda/bin/python setup.py develop chdir=/vagrant"